# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Use vim keybindings in copy mode
set -g mode-keys vi

# Show different accent colors locally and over SSH
if-shell '[ -n "$SSH_TTY" ]' \
  'set -g @accent orange' \
  'set -g @accent green'

# Status (show hostname over SSH)
if-shell '[ -n "$SSH_TTY" ]' \
  'set -g status-left "#[bg=#{@accent},fg=black] #S in #h #[bg=default] "' \
  'set -g status-left "#[bg=#{@accent},fg=black] #S #[bg=default] "'
set -g status-left-length 100
set -g status-right ""
set -g status-style "bg=black"

# Windows
set -g window-status-style "fg=#{@accent},dim"
set -g window-status-current-style "fg=#{@accent},nodim"
