# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Use vim keybindings in copy mode
set -g mode-keys vi

### Theme

set -g @accent-color              green
set -g @accent-color-status-right yellow

set -g status-style "bg=black"

set -g status-left "#[bg=#{@accent-color},fg=black] #S #[bg=default] "
set -g status-left-length 100

set -g window-status-style "fg=#{@accent-color},dim"
set -g window-status-current-style "fg=#{@accent-color},nodim"

if-shell '[ -n "$SSH_TTY" ]' \
  'set -g status-right "#[fg=#{@accent-color-status-right}] %H:%M %d-%b-%y #[bg=#{@accent-color-status-right},fg=black] #h "' \
  'set -g status-right ""'
